### ISSUE TITLE
Z-wave devices

### ISSUE THREAD

**Issue by adrum** [craigjmidwinter/total-connect-client#97]
Is there any way we can control and read the state of zwave devices? Specifically, door locks?

**Comment by austinmroczek** [comment]
Please describe your use case.  Are you trying to control zwave using only your zwave enabled panel?  There will be a 5-10 second delay by controlling through this API.  If timing is important, or possibility of control when Internet is down,  you may want a zwave controller attached to whatever is running your Home Assistant.

We'll have to look at https://rs.alarmnet.com/TC21api/tc2.asmx?op=GetAutomationDeviceStatus or maybe https://rs.alarmnet.com/TC21api/tc2.asmx?op=GetDeviceStatus in order to get info about the lock first.  Then likely https://rs.alarmnet.com/TC21api/tc2.asmx?op=ControlALock to control it.

Likely these service calls will depend on your service level with your alarm company, but we won't know until we try.

**Comment by austinmroczek** [comment]
@adrum please see comment above.  If you're still interested, I'd need your help to test new code.  If not, we can close this issue.

**Comment by adrum** [comment]
@austinmroczek I'm definitely still interested! Sorry for the radio silence. I understand the delay issues and connectivity concerns, but I'm willing to accept it. 

I have gone down the path of trying to setup zwave2mqtt as a secondary controller, but not of the nodes on my TC panel came over.

Just let me know what you need me to test.

**Comment by austinmroczek** [comment]
Ok first please follow the troubleshooting instructions on the readme and post your system info here.

**Comment by adrum** [comment]
```
Username: <redacted>
Password: <redacted>
Usercode: {'default': '-1'}
Auto Bypass Low Battery: False
Valid Credentials: True
Module Flags:
  Security: 1
  Video: 1
  Automation: 1
  GPS: 1
  VideoPIR: 1
  ReadState: 1
  IsAlexaEnabled: 1
Username: <redacted>
UserID: <redacted>
Master User: True
User Administrator: True
Configuration Administrator: True
User features:
  Master: 1
  User Administration: 1
  Configuration Administration: 1

LOCATIONS: 1

LOCATION <redacted>

PhotoURL: None
SecurityDeviceID: 3395004
DeviceList: OrderedDict([('DeviceInfoBasic', [OrderedDict([('DeviceID', <redacted>), ('DeviceName', 'Security System'), ('DeviceClassID', 1), ('DeviceSerialNumber', '<redacted>'), ('DeviceFlags', 'PromptForUserCode=0,PromptForInstallerCode=0,PromptForImportSecuritySettings=0,AllowUserSlotEditing=0,CalCapable=1,CanBeSentToPanel=1,CanArmNightStay=0,CanSupportMultiPartition=0,PartitionCount=0,MaxPartitionCount=0,OnBoardingSupport=0,PartitionAdded=0,DuplicateUserSyncStatus=0,PanelType=10,PanelVariant=1,BLEDisarmCapable=0,ArmHomeSupported=0,DuplicateUserCodeCheck=1,CanSupportRapid=0,IsKeypadSupported=1,WifiEnrollmentSupported=1,IsConnectedPanel=0,ArmNightInSceneSupported=0,BuiltInCameraSettingsSupported=1,ZWaveThermostatScheduleDisabled=0,MultipleAuthorityLevelSupported=0,VideoOnPanelSupported=0'), ('SecurityPanelTypeID', None), ('DeviceSerialText', None)]), OrderedDict([('DeviceID', 3401019), ('DeviceName', 'Automation'), ('DeviceClassID', 3), ('DeviceSerialNumber', '<redacted>'), ('DeviceFlags', None), ('SecurityPanelTypeID', None), ('DeviceSerialText', None)]), OrderedDict([('DeviceID', 148638), ('DeviceName', 'Front Door'), ('DeviceClassID', 302), ('DeviceSerialNumber', '241'), ('DeviceFlags', 'PrerequisiteDeviceID=3401019,PrerequisiteDeviceClassID=3'), ('SecurityPanelTypeID', None), ('DeviceSerialText', None)]), OrderedDict([('DeviceID', 152306), ('DeviceName', 'Back Door'), ('DeviceClassID', 302), ('DeviceSerialNumber', '240'), ('DeviceFlags', 'PrerequisiteDeviceID=3401019,PrerequisiteDeviceClassID=3'), ('SecurityPanelTypeID', None), ('DeviceSerialText', None)]), OrderedDict([('DeviceID', 3395005), ('DeviceName', 'Built-In Camera'), ('DeviceClassID', 6), ('DeviceSerialNumber', '<redacted>'), ('DeviceFlags', None), ('SecurityPanelTypeID', None), ('DeviceSerialText', None)]), OrderedDict([('DeviceID', 3395003), ('DeviceName', 'Video DoorBell'), ('DeviceClassID', 7), ('DeviceSerialNumber', '<redacted>'), ('DeviceFlags', None), ('SecurityPanelTypeID', None), ('DeviceSerialText', None)])])])
AcLoss: False
LowBattery: False
IsCoverTampered: False
Arming State: 10200
LocationModuleFlags:
  Security: 1
  Video: 0
  Automation: 1
  GPS: 0
  VideoPIR: 1
  TimeTriggeredEvent: 1
  TemperatureUnits: F
  ConfigureContent: 1
  SyncLocation: 0
  ConfigureSlideshow: 0
  TimezoneOffset: -4.0
  SmartAction: 1
  CustomArm: 0
  NoTriggerScene: 1
  NoScene: 1
  AutoSyncEnabled: 1
  WiFIThermostatEnabled: 1
  SupportsOnlyHDPhotos: 1
  SyncStatusSupported: 1
  WiFiHBSupported: 1
  DoorBellSupported: 1
  masterUserCodeSync: 0
  GeofenceStatus: 2
  RSISupported: 0
  VideoServiceEnabled: 0
  HasAddressUpdated: 1
  WifiGaragedoorSupported: 1
  OutboundServiceEnabled: 0
  HasSmartScenes: 1
  MotionViewerServiceEnabled: 0
  VavEnabled: 0
  UserManagementDisabled: 0

ZONES: 19

Zone 3 - Front Door
Partition: 1	Type: 1	Status: 0

Zone 4 - Back Door
Partition: 1	Type: 1	Status: 0

Zone 5 - Kitchen Door
Partition: 1	Type: 1	Status: 0

Zone 6 - Living Room Motion Sensor
Partition: 1	Type: 4	Status: 0

Zone 280 - Temperature
Partition: 1	Type: 12	Status: 0

Zone 281 - Temperature
Partition: 1	Type: 12	Status: 0

Zone 282 - Temperature
Partition: 1	Type: 12	Status: 0

Zone 283 - Temperature
Partition: 1	Type: 12	Status: 0

Zone 284 - Temperature
Partition: 1	Type: 12	Status: 0

Zone 285 - Temperature
Partition: 1	Type: 12	Status: 0

Zone 286 - Temperature
Partition: 1	Type: 12	Status: 0

Zone 287 - Temperature
Partition: 1	Type: 12	Status: 0

Zone 288 - Temperature
Partition: 1	Type: 12	Status: 0

Zone 289 - Temperature
Partition: 1	Type: 12	Status: 0

Zone 290 - Temperature
Partition: 1	Type: 12	Status: 0

Zone 291 - Temperature
Partition: 1	Type: 12	Status: 0

Zone 995 - Fire
Partition: 1	Type: 9	Status: 0

Zone 998 - Local Alarm
Partition: 1	Type: 89	Status: 0

Zone 999 - Police
Partition: 1	Type: 6	Status: 0
```
